//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/* Generated Source: Do Not Modify */
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TurndownSchedule) DeepCopyInto(out *TurndownSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TurndownSchedule.
func (in *TurndownSchedule) DeepCopy() *TurndownSchedule {
	if in == nil {
		return nil
	}
	out := new(TurndownSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TurndownSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TurndownScheduleList) DeepCopyInto(out *TurndownScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TurndownSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TurndownScheduleList.
func (in *TurndownScheduleList) DeepCopy() *TurndownScheduleList {
	if in == nil {
		return nil
	}
	out := new(TurndownScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TurndownScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TurndownScheduleSpec) DeepCopyInto(out *TurndownScheduleSpec) {
	*out = *in
	in.Start.DeepCopyInto(&out.Start)
	in.End.DeepCopyInto(&out.End)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TurndownScheduleSpec.
func (in *TurndownScheduleSpec) DeepCopy() *TurndownScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(TurndownScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TurndownScheduleStatus) DeepCopyInto(out *TurndownScheduleStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	in.ScaleDownTime.DeepCopyInto(&out.ScaleDownTime)
	if in.ScaleDownMetadata != nil {
		in, out := &in.ScaleDownMetadata, &out.ScaleDownMetadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ScaleUpTime.DeepCopyInto(&out.ScaleUpTime)
	if in.ScaleUpMetadata != nil {
		in, out := &in.ScaleUpMetadata, &out.ScaleUpMetadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TurndownScheduleStatus.
func (in *TurndownScheduleStatus) DeepCopy() *TurndownScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(TurndownScheduleStatus)
	in.DeepCopyInto(out)
	return out
}
