version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.22.3

    working_directory: /home/circleci/go/src/github.com/kubecost/cluster-turndown
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...